name: "HCL AppScan CodeSweep"

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main  # Or your default branch

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run AppScan CodeSweep
        uses: HCL-TECH-SOFTWARE/appscan-codesweep-action@v2.1

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      APPSCAN_API_KEY: ${{ secrets.APPSCAN_API_KEY }}
